import {copy,projects,dimensions,pageHref,type Locale,type ProjectId} from './content.ts';
import {galleryCopy} from './gallery-copy.ts';
// Kept separate from renderPage so the same grounded content serves static and dialog views.
const e = (s:string) => s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const ext = (href:string,label:string) => `<a class="text-link" href="${href}" target="_blank" rel="noopener noreferrer">${e(label)} <span aria-hidden="true">↗</span></a>`;
export function catalogue(locale:Locale) {
  const c=copy[locale];
  return `<div class="project-grid">${projects.map((p,i)=>`<article class="project-card project-${p.id}"><a class="project-visual image-shell" href="${pageHref(p.id,locale,false)}" data-case="${p.id}" aria-label="${p.name} — ${e(c.caseStudy)}"><img src="assets/${p.id}-preview.webp" alt="${e(c.project[p.id].alt)}" width="${dimensions[p.id].preview[0]}" height="${dimensions[p.id].preview[1]}" loading="lazy"></a><div class="project-description"><span class="eyebrow">${String(i+1).padStart(2,'0')} / ${e(c.project[p.id].category)}</span><div class="project-title"><h3><a data-case="${p.id}" href="${pageHref(p.id,locale,false)}">${p.name}</a></h3><a data-case="${p.id}" href="${pageHref(p.id,locale,false)}" class="case-arrow" aria-label="${p.name} — ${e(c.caseStudy)}">↗</a></div><p>${e(c.project[p.id].summary)}</p><div class="project-links">${ext(p.live,c.live)}${ext(p.source,c.source)}</div></div></article>`).join('')}</div>`;
}
export function galleryHero(locale:Locale) {
  const c=copy[locale],g=galleryCopy[locale];
  return `<section class="pavilion" aria-label="${e(g.label)}"><div class="pavilion-heading"><p class="eyebrow">${g.label} <span aria-hidden="true">/ 01—08</span></p><h1>${g.title}</h1><p class="pavilion-identity">${e(c.name)} <span>/</span> seoshiro</p><p class="pavilion-intro">${g.intro}</p><a class="enter-link" href="#work">${g.enter}<span aria-hidden="true">↗</span></a></div><div class="gallery-stage"><canvas id="gallery-canvas" aria-hidden="true"></canvas><div class="gallery-hotspots" role="group" aria-label="${e(g.hint)}">${projects.map(p=>`<a class="hotspot" href="${pageHref(p.id,locale,false)}" data-exhibit="${p.id}" aria-label="${p.name} — ${e(c.caseStudy)}"><span class="hotspot-dot" aria-hidden="true">+</span><span>${p.name}</span></a>`).join('')}<a class="hotspot" href="#about" data-exhibit="about">${c.about} <span aria-hidden="true">↗</span></a></div><p class="gallery-status" role="status">${g.loading}</p><div class="entrance-shade" aria-hidden="true"></div></div><div class="gallery-toolbar" hidden><p><span class="status-dot" aria-hidden="true"></span>${g.hint}</p><div class="viewpoints" role="group" aria-label="${e(g.focus)}"><button type="button" data-view="overview" aria-pressed="true">${g.overview}</button><button type="button" data-view="objects" aria-pressed="false">${g.objects}</button><button type="button" data-view="tools" aria-pressed="false">${g.tools}</button></div><a href="#work">${g.catalogue} <span aria-hidden="true">↗</span></a></div><div class="exhibit-rail" role="group" aria-label="${g.hint}">${projects.map(p=>`<a href="${pageHref(p.id,locale,false)}" data-exhibit="${p.id}">${p.name}<span aria-hidden="true">↗</span></a>`).join('')}</div><p class="gallery-fallback">${g.fallback}</p></section>`;
}
export function dialogContent(locale:Locale,id:ProjectId|'work'|'about'|'contact') {
  const c=copy[locale],g=galleryCopy[locale];
  if(id==='work') return `<p class="eyebrow">01—08 / ${c.work}</p><h2 id="dialog-title">${g.catalogue}</h2><p>${c.selectedNote}</p>${catalogue(locale)}`;
  if(id==='about') return `<p class="eyebrow">${c.aboutLabel}</p><h2 id="dialog-title">${e(c.name)}</h2><p class="dialog-lead">${e(c.aboutText)}</p><ol class="principles">${c.principles.map((p,i)=>`<li><span>0${i+1}</span><div><h3>${e(p.title)}</h3><p>${e(p.text)}</p></div></li>`).join('')}</ol><p class="tech-line">TypeScript / React / Browser APIs</p>`;
  if(id==='contact') return `<p class="eyebrow">${c.contact}</p><h2 id="dialog-title">${e(c.contactTitle).replace(/\n/g,'<br>')}</h2><p class="dialog-lead">${e(c.contactText)}</p>${ext('https://github.com/seoshiro',c.github)}<p class="contact-identity">${e(c.name)} / seoshiro</p>`;
  const p=projects.find(p=>p.id===id)!,t=c.project[id];
  return `<div class="dialog-case-meta"><p class="eyebrow">${e(t.category)}</p><span class="eyebrow">${String(projects.indexOf(p)+1).padStart(2,'0')} / 08</span></div><h2 id="dialog-title">${p.name}</h2><p class="dialog-lead">${e(t.summary)}</p><div class="case-actions">${ext(p.live,c.live)}${ext(p.source,c.source)}</div><figure class="dialog-cover image-shell"><img src="assets/${id}.webp" alt="${e(t.alt)}" width="${dimensions[id].main[0]}" height="${dimensions[id].main[1]}"><figcaption>${e(t.caption)}</figcaption></figure><div class="dialog-io"><div><h3>${c.input}</h3><p>${e(t.input)}</p></div><div><h3>${c.output}</h3><p>${e(t.output)}</p></div></div><h3>${c.engineering}</h3><ol class="dialog-decisions">${t.decisions.map(s=>`<li>${e(s)}</li>`).join('')}</ol><h3>${c.boundaries}</h3><p>${e(t.limit)}</p><div class="case-actions">${ext(p.evidence,c.evidence)}<a class="text-link" href="${pageHref(id,locale,false)}">${g.full} →</a></div><ul class="tags">${p.stack.map(s=>`<li>${e(s)}</li>`).join('')}</ul>`;
}
